version: '3.8'

services:
  pyoxidizer:
    image: myapp-manylinux-build-env
    volumes:
      - ${SOURCE_DIR}:${SOURCE_DIR}:rw
      - ${WHEEL_DIR}:${WHEEL_DIR}:rw
    environment:
      - WHEEL_DIR=${WHEEL_DIR}
      - DIST_DIR=${DIST_DIR}
      - SOURCE_DIR=${SOURCE_DIR}
    command: /bin/bash -c "${SOURCE_DIR}/packaging/pyoxidizer/build.sh"

  nuitka:
    image: myapp-manylinux-build-env
    volumes:
      - ${SOURCE_DIR}:${SOURCE_DIR}:rw
      - ${WHEEL_DIR}:${WHEEL_DIR}:rw
    environment:
      - WHEEL_DIR=${WHEEL_DIR}
      - BUILD_DIR=${BUILD_DIR}
      - DIST_DIR=${DIST_DIR}
    command: /bin/bash -c "${SOURCE_DIR}/packaging/nuitka/build.sh"

  appimage:
    image: myapp-manylinux-build-env
    volumes:
      - ${SOURCE_DIR}:${SOURCE_DIR}:rw
      - ${WHEEL_DIR}:${WHEEL_DIR}:rw
    environment:
      - WHEEL_DIR=${WHEEL_DIR}
      - BUILD_DIR=${BUILD_DIR}
      - DIST_DIR=${DIST_DIR}
    command: /bin/bash -c "${SOURCE_DIR}/packaging/appimage/build.sh"

  pex:
    image: myapp-manylinux-build-env
    volumes:
      - ${SOURCE_DIR}:${SOURCE_DIR}:rw
      - ${WHEEL_DIR}:${WHEEL_DIR}:rw
    environment:
      - WHEEL_DIR=${WHEEL_DIR}
      - BUILD_DIR=${BUILD_DIR}
      - DIST_DIR=${DIST_DIR}
    command: /bin/bash -c "${SOURCE_DIR}/packaging/pex/build.sh"
